### ISSUE TITLE
No need for get_all_substrings

### ISSUE THREAD

**Issue by jembishop** [jonnyspicer/jonnyspicer.github.io#2]
no need for get_all_substrings, ```in``` works for checking string is substring.

```python 
>>> 'men' in 'mendokusai'
True
```
or if looking for start:
```python 
>>> 'mendokusai'.startswith('men')
True
```

**Comment by jonnyspicer** [comment]
Makes sense, thanks - is this because python treats strings more like a list of chars than an a separate datatype?

**Comment by jembishop** [comment]
Yes, under the hood it treats them as arrays of chars uses this algorithm for matching https://www.youtube.com/watch?v=PHXAOKQk2dw.

**Comment by jonnyspicer** [comment]
Good to know, cheers :)

**Comment by jonnyspicer** [comment]
Actually fixed this as of latest commit on master, fittingly a whole year to the day :D better late than never?
